### ISSUE TITLE
callee of deserializeHeader() doesn't handle error

### ISSUE THREAD

**Issue by ralphtheninja** [noffle/multifeed#11]
`deserializeHeader()` might return an `Error` if json is borked, but this it not taken care of by the callee.

https://github.com/noffle/multifeed/blob/3d2e999454363d3e123504efee57188ec862bf91/index.js#L291-L303

https://github.com/noffle/multifeed/blob/3d2e999454363d3e123504efee57188ec862bf91/index.js#L211-L231

**Comment by ralphtheninja** [comment]
We could just return `null` from `deserializeHeader()` and the callee should bail unless `header` is ok.

**Comment by ralphtheninja** [comment]
I'm guessing we assume that the `header` contains _both_ `header.version` and `header.keys`?

**Comment by noffle** [comment]
fixed in 2.0.4
