### ISSUE TITLE
Fix tests on Travis

### ISSUE THREAD

**Issue by ralphtheninja** [noffle/multifeed#13]

**Comment by ralphtheninja** [comment]
https://github.com/noffle/multifeed/commit/51739d4bc8eee414a449bfe21dd1d0b06bce4810

**Comment by noffle** [comment]
ha, yep! not sure yet how to get your PRs to rebuild /w the updated travis file. restarting the build FROM travis just uses the old versions

**Comment by ralphtheninja** [comment]
@noffle I rebased them on latest master, so should be good.
